name: Mlops CI


on:
  push:
    branches: 
      - main
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11.5' 
      
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
