name: Mlops CI


on:
  push:
    branches: 
      - main
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11.5' 
      
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Processing
        run: |
          python src/data/run_processing.py   
            --input data/raw/house_data.csv   
            --output data/processed/cleaned_house_data.csv

      - name: Feature Engineering
        run: |
          python src/features/engineer.py   
            --input data/processed/cleaned_house_data.csv 
            --output data/processed/featured_house_data.csv   --preprocessor models/trained/preprocessor.pkl

      # - name: Train the model
      #   run: |
      #     python src/models/train_model.py   
      #     --config configs/model_config.yaml   
      #     --data data/processed/featured_house_data.csv   
      #     --models-dir models   
      #     --mlflow-tracking-uri http://localhost:5555